### ISSUE TITLE
na rohlik.cz se zobrazi graf jen pro prvni produkt

### ISSUE THREAD

**Issue by martenson** [topmonks/hlidac-shopu#116]
Nasledujici produkty uz jen loguji chybu do konzole (a zobrazuji graf z prvniho produktu). Chrome Version 86.0.4240.183 (Official Build) (x86_64); macos 10.14.6

```
DOMException: Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.
    at renderHTML (chrome-extension://plmlonggbfebcjelncogcnclagkmkikk/content.js:17498:31)
    at chrome-extension://plmlonggbfebcjelncogcnclagkmkikk/content.js:17529:9
```

edit: Jeste v logu po zavreni modalu pribude:

```
Error: Element to add chart not found
    at Rohlik.inject (content.js:17129)
    at renderHTML (content.js:17493)
    at content.js:17529
```

**Comment by rarous** [comment]
@martenson díky za report, pracuju na opravě. Týká se skoro všech asynchronně načítaných detailů. Během dneška bude oprava venku.
